"""Create wishes table.

Revision ID: b0fca6adf5f3
Revises: d00a442ec5ac
Create Date: 2024-07-28 18:07:38.094263+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "b0fca6adf5f3"
down_revision: Union[str, None] = "d00a442ec5ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wishes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("user_telegram_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_telegram_id"],
            ["users.telegram_id"],
            name=op.f("fk_wishes_user_telegram_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wishes")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wishes")
    # ### end Alembic commands ###
